/* eslint-disable @typescript-eslint/no-unused-vars */
import { ReleaseGroup } from "../../src/release-group";
const releasesGroup: ReleaseGroup = {
	"secondary-type-ids": ["0c60f497-ff81-3818-befd-abfc84a4858b"],
	relations: [
		{
			type: "mashes up",
			direction: "forward",
			"attribute-ids": {},
			"type-id": "03786c2a-cd9d-4148-b3ea-35ea61de1283",
			end: null,
			"source-credit": "",
			attributes: [],
			ended: false,
			begin: null,
			"target-credit": "",
			"target-type": "release_group",
			"attribute-values": {},
			release_group: {
				"artist-credit": [
					{
						artist: {
							"sort-name": "JAY‐Z",
							id: "f82bcf78-5b69-4622-a5ef-73800768d9ac",
							"type-id": null,
							disambiguation: "US rapper",
							name: "JAY‐Z",
							type: null,
						},
						name: "Jay‐Z",
						joinphrase: "",
					},
				],
				id: "77befaa0-662e-3d84-ba45-c862e16dc109",
				disambiguation: "",
				"primary-type": null,
				"primary-type-id": null,
				releases: [],
				"secondary-type-ids": [],
				title: "The Black Album",
				"secondary-types": [],
				"first-release-date": "2003-11-17",
			},
		},
		{
			type: "mashes up",
			direction: "forward",
			"attribute-ids": {},
			"type-id": "03786c2a-cd9d-4148-b3ea-35ea61de1283",
			end: null,
			"source-credit": "",
			attributes: [],
			begin: null,
			ended: false,
			"target-type": "release_group",
			"target-credit": "",
			"attribute-values": {},
			release_group: {
				disambiguation: "“The White Album”",
				id: "055be730-dcad-31bf-b550-45ba9c202aa3",
				"primary-type-id": null,
				releases: [],
				"primary-type": null,
				"artist-credit": [
					{
						name: "The Beatles",
						joinphrase: "",
						artist: {
							type: null,
							disambiguation: "",
							"type-id": null,
							id: "b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d",
							"sort-name": "Beatles, The",
							name: "The Beatles",
						},
					},
				],
				title: "The Beatles",
				"first-release-date": "1968-11-22",
				"secondary-types": [],
				"secondary-type-ids": [],
			},
		},
		{
			"attribute-ids": {},
			direction: "forward",
			url: {
				resource: "https://www.discogs.com/master/52188",
				id: "c22c6f4b-b65a-4f1d-93e1-1422ead5560d",
			},
			type: "discogs",
			end: null,
			"type-id": "99e550f3-5ab4-3110-b5b9-fe01d970b126",
			ended: false,
			begin: null,
			"source-credit": "",
			attributes: [],
			"attribute-values": {},
			"target-credit": "",
			"target-type": "url",
		},
		{
			"target-credit": "",
			"target-type": "url",
			"attribute-values": {},
			attributes: [],
			"source-credit": "",
			ended: false,
			begin: null,
			"type-id": "b988d08c-5d86-4a57-9557-c83b399e3580",
			end: null,
			url: {
				resource: "https://www.wikidata.org/wiki/Q661738",
				id: "2ae260bd-8448-43ba-927b-ddb2c2ca1181",
			},
			type: "wikidata",
			"attribute-ids": {},
			direction: "forward",
		},
	],
	rating: { "votes-count": 1, value: 4 },
	annotation: null,
	"primary-type": "Album",
	"primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
	title: "The Grey Album",
	"secondary-types": ["Remix"],
	"first-release-date": "2004-02",
	tags: [
		{ name: "cut-up dj", count: 4 },
		{ name: "experimental", count: 3 },
		{ name: "gangsta", count: 1 },
		{ name: "hip hop", count: 4 },
		{ count: 2, name: "hip hop rap" },
		{ name: "hip-hop", count: 1 },
		{ count: 2, name: "mash up" },
		{ name: "mashup", count: 2 },
	],
	aliases: [],
	"artist-credit": [
		{
			artist: {
				"type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
				disambiguation: "Brian Burton",
				genres: [
					{
						id: "52faa157-6bad-4d86-a0ab-d4dec7d2513c",
						disambiguation: "",
						count: 2,
						name: "hip hop",
					},
				],
				id: "4b356f05-bcc2-4544-925b-fd9a1bf708be",
				"sort-name": "Danger Mouse",
				aliases: [
					{
						"type-id": null,
						"sort-name": "DJ Danger Mouse",
						name: "DJ Danger Mouse",
						end: null,
						primary: null,
						locale: null,
						type: null,
						ended: false,
						begin: null,
					},
					{
						type: null,
						locale: null,
						primary: null,
						begin: null,
						ended: false,
						"type-id": null,
						"sort-name": "DJ Dangermouse",
						end: null,
						name: "DJ Dangermouse",
					},
					{
						name: "Danger Mouse, DJ",
						end: null,
						"type-id": null,
						"sort-name": "Danger Mouse, DJ",
						ended: false,
						begin: null,
						primary: null,
						locale: null,
						type: null,
					},
					{
						end: null,
						name: "Dangermouse",
						"sort-name": "Dangermouse",
						"type-id": null,
						begin: null,
						ended: false,
						type: null,
						locale: null,
						primary: null,
					},
				],
				tags: [
					{ name: "batteur", count: 1 },
					{ count: 1, name: "drummer" },
					{ name: "hip hop", count: 2 },
					{ name: "producer", count: 1 },
					{ count: 1, name: "producteur" },
				],
				name: "Danger Mouse",
				type: "Person",
			},
			name: "Danger Mouse",
			joinphrase: "",
		},
	],
	genres: [
		{
			id: "68c81274-5770-4e7b-a4bf-ab0d7d425d99",
			disambiguation: "",
			count: 3,
			name: "experimental",
		},
		{
			id: "52faa157-6bad-4d86-a0ab-d4dec7d2513c",
			disambiguation: "",
			count: 4,
			name: "hip hop",
		},
	],
	id: "5d9261c0-3ccf-3154-b331-ddde4c7b8ee0",
	disambiguation: "",
	releases: [
		{
			"release-events": [
				{
					area: {
						type: null,
						name: "United States",
						"iso-3166-1-codes": ["US"],
						"type-id": null,
						id: "489ce91b-6658-3307-9877-795b68554c98",
						disambiguation: "",
						"sort-name": "United States",
					},
					date: "2004-02",
				},
			],
			date: "2004-02",
			status: "Bootleg",
			"status-id": "1156806e-d06a-38bd-83f0-cf2284a808b9",
			"packaging-id": null,
			"text-representation": { script: "Latn", language: "eng" },
			title: "The Grey Album",
			barcode: null,
			country: "US",
			id: "bcedbdb0-8e2a-40f8-b388-90932b21435d",
			genres: [],
			disambiguation: "",
			packaging: null,
			quality: "normal",
			aliases: [],
			tags: [{ count: 1, name: "mash up" }],
		},
		{
			"packaging-id": null,
			"status-id": "1156806e-d06a-38bd-83f0-cf2284a808b9",
			status: "Bootleg",
			date: "2004-02",
			"release-events": [
				{
					date: "2004-02",
					area: {
						type: null,
						name: "[Worldwide]",
						"sort-name": "[Worldwide]",
						id: "525d4e18-3d00-31b9-a58b-a146a916de8f",
						disambiguation: "",
						"type-id": null,
						"iso-3166-1-codes": ["XW"],
					},
				},
			],
			tags: [{ name: "downloadable", count: 1 }],
			packaging: null,
			aliases: [],
			quality: "normal",
			country: "XW",
			genres: [],
			disambiguation: "",
			id: "b50e5d5f-8e5a-3ec3-9d7d-be41871e9f97",
			barcode: null,
			"text-representation": { language: "eng", script: "Latn" },
			title: "The Grey Album",
		},
		{
			status: "Promotion",
			date: "2004",
			"release-events": [
				{
					date: "2004",
					area: {
						"type-id": null,
						id: "489ce91b-6658-3307-9877-795b68554c98",
						disambiguation: "",
						"sort-name": "United States",
						"iso-3166-1-codes": ["US"],
						name: "United States",
						type: null,
					},
				},
			],
			"packaging-id": null,
			"status-id": "518ffc83-5cde-34df-8627-81bff5093d92",
			barcode: "",
			title: "The Grey Album",
			"text-representation": { language: "eng", script: "Latn" },
			tags: [],
			quality: "normal",
			aliases: [],
			packaging: null,
			genres: [],
			disambiguation: "",
			id: "0c34b423-f28f-4f00-8e10-01aedde37fb0",
			country: "US",
		},
		{
			"release-events": [
				{
					date: "2012-12",
					area: {
						type: null,
						disambiguation: "",
						"type-id": null,
						id: "525d4e18-3d00-31b9-a58b-a146a916de8f",
						"sort-name": "[Worldwide]",
						"iso-3166-1-codes": ["XW"],
						name: "[Worldwide]",
					},
				},
			],
			status: "Bootleg",
			date: "2012-12",
			"status-id": "1156806e-d06a-38bd-83f0-cf2284a808b9",
			"packaging-id": "119eba76-b343-3e02-a292-f0f00644bb9b",
			"text-representation": { language: "eng", script: "Latn" },
			title: "The Grey Album",
			barcode: "",
			country: "XW",
			genres: [],
			id: "7ed0f1d9-b5e9-4389-bc83-d453b0302529",
			disambiguation: "remaster",
			tags: [],
			packaging: "None",
			aliases: [],
			quality: "normal",
		},
	],
};
